# Generated by Django 2.1.5 on 2019-05-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalPay', '0002_userregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='enroll',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
