# Generated by Django 2.1.5 on 2019-05-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalPay', '0003_auto_20190520_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='cpassword',
        ),
        migrations.AlterField(
            model_name='userregister',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
