# Generated by Django 2.1.5 on 2019-05-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalPay', '0004_auto_20190521_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('msg', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
