# Generated by Django 2.1.5 on 2019-05-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalPay', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=30)),
                ('cvv', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'card',
            },
        ),
    ]
