# Generated by Django 2.1.5 on 2019-05-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalPay', '0006_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='enroll',
            field=models.CharField(default='', max_length=30),
        ),
    ]
