# Generated by Django 2.1.5 on 2019-05-22 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SalPay', '0007_card_enroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='paid_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
